# LAB | Ensemble Methods

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In this Lab, you should try different ensemble methods in order to see if can obtain a better model than before. In order to do a fair comparison, you should perform the same feature scaling, engineering applied in previous Lab.

In [2]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

Now perform the same as before:
- Feature Scaling
- Feature Selection


In [12]:
spaceship.dropna(inplace=True)
spaceship['Cabin'] = spaceship['Cabin'].str[0]
spaceship.drop(['PassengerId', 'Name'], axis=1, inplace=True)

In [44]:
numerical_columns = spaceship.select_dtypes(include=[np.number]).columns
numerical_columns = ['Age', 'FoodCourt', 'VRDeck']

In [54]:
from sklearn.preprocessing import MinMaxScaler

# Assuming numerical_columns contains your numerical columns
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(spaceship[numerical_columns])

# Convert scaled_data back to a DataFrame
numerical_scaled_df = pd.DataFrame(scaled_data, columns=numerical_columns)


In [56]:
numerical_scaled_df

Age  FoodCourt    VRDeck
0     0.493671   0.000000  0.000000
1     0.303797   0.000302  0.002164
2     0.734177   0.119948  0.002410
3     0.417722   0.043035  0.009491
4     0.202532   0.002348  0.000098
...        ...        ...       ...
6601  0.518987   0.228726  0.003639
6602  0.227848   0.000000  0.000000
6603  0.329114   0.000000  0.000000
6604  0.405063   0.035186  0.159077
6605  0.556962   0.157247  0.000590

[6606 rows x 3 columns]

In [58]:
categorical_columns = spaceship.select_dtypes(include=[object]).columns
categorical_columns = ['HomePlanet', 'CryoSleep', 'Destination', 'VIP']

In [60]:
categorical_dummies_df = pd.get_dummies(spaceship[categorical_columns], columns=categorical_columns)

In [62]:
categorical_dummies_df

HomePlanet_Earth  HomePlanet_Europa  HomePlanet_Mars  CryoSleep_False  \
0                False               True            False             True   
1                 True              False            False             True   
2                False               True            False             True   
3                False               True            False             True   
4                 True              False            False             True   
...                ...                ...              ...              ...   
8688             False               True            False             True   
8689              True              False            False            False   
8690              True              False            False             True   
8691             False               True            False             True   
8692             False               True            False             True   

      CryoSleep_True  Destination_55 Cancri e  Destination_PSO J318.5-22  \
0              False                    False                      False   
1              False                    False                      False   
2              False                    False                      False   
3              False                    False                      False   
4              False                    False                      False   
...              ...                      ...                        ...   
8688           False                     True                      False   
8689            True                    False                       True   
8690           False                    False                      False   
8691           False                     True                      False   
8692           False                    False                      False   

      Destination_TRAPPIST-1e  VIP_False  VIP_True  
0                        True       True     False  
1                        True       True     False  
2                        True      False      True  
3                        True       True     False  
4                        True       True     False  
...                       ...        ...       ...  
8688                    False      False      True  
8689                    False       True     False  
8690                     True       True     False  
8691                    False       True     False  
8692                     True       True     False  

[6606 rows x 10 columns]

In [66]:
pd.concat([numerical_scaled_df, categorical_dummies_df], axis=1)
target = spaceship['Transported']
features

Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0     39.0          0.0        0.0           0.0     0.0     0.0   
1     24.0        109.0        9.0          25.0   549.0    44.0   
2     58.0         43.0     3576.0           0.0  6715.0    49.0   
3     33.0          0.0     1283.0         371.0  3329.0   193.0   
4     16.0        303.0       70.0         151.0   565.0     2.0   
...    ...          ...        ...           ...     ...     ...   
8688  41.0          0.0     6819.0           0.0  1643.0    74.0   
8689  18.0          0.0        0.0           0.0     0.0     0.0   
8690  26.0          0.0        0.0        1872.0     1.0     0.0   
8691  32.0          0.0     1049.0           0.0   353.0  3235.0   
8692  44.0        126.0     4688.0           0.0     0.0    12.0   

      HomePlanet_Earth  HomePlanet_Europa  HomePlanet_Mars  CryoSleep_False  \
0                False               True            False             True   
1                 True              False            False             True   
2                False               True            False             True   
3                False               True            False             True   
4                 True              False            False             True   
...                ...                ...              ...              ...   
8688             False               True            False             True   
8689              True              False            False            False   
8690              True              False            False             True   
8691             False               True            False             True   
8692             False               True            False             True   

      ...  Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  \
0     ...    False    False    False    False    False   
1     ...    False    False     True    False    False   
2     ...    False    False    False    False    False   
3     ...    False    False    False    False    False   
4     ...    False    False     True    False    False   
...   ...      ...      ...      ...      ...      ...   
8688  ...    False    False    False    False    False   
8689  ...    False    False    False     True    False   
8690  ...    False    False    False     True    False   
8691  ...    False     True    False    False    False   
8692  ...    False     True    False    False    False   

      Destination_55 Cancri e  Destination_PSO J318.5-22  \
0                       False                      False   
1                       False                      False   
2                       False                      False   
3                       False                      False   
4                       False                      False   
...                       ...                        ...   
8688                     True                      False   
8689                    False                       True   
8690                    False                      False   
8691                     True                      False   
8692                    False                      False   

      Destination_TRAPPIST-1e  VIP_False  VIP_True  
0                        True       True     False  
1                        True       True     False  
2                        True      False      True  
3                        True       True     False  
4                        True       True     False  
...                       ...        ...       ...  
8688                    False      False      True  
8689                    False       True     False  
8690                     True       True     False  
8691                    False       True     False  
8692                     True       True     False  

[6606 rows x 24 columns]

**Perform Train Test Split**

In [69]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=0)

**Model Selection** - now you will try to apply different ensemble methods in order to get a better model

- Bagging and Pasting

In [76]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

# Initialize a base classifier (e.g., Decision Tree)
base_classifier = DecisionTreeClassifier(random_state=0)

# Initialize Bagging Classifier
bagging_clf = BaggingClassifier(base_classifier, n_estimators=10, random_state=0)

# Fit the Bagging Classifier on the training data
bagging_clf.fit(X_train, y_train)

# Predict on the test data
y_pred = bagging_clf.predict(X_test)

# Calculate and print performance metrics
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.78
Classification Report:
              precision    recall  f1-score   support

       False       0.78      0.80      0.79       661
        True       0.79      0.77      0.78       661

    accuracy                           0.78      1322
   macro avg       0.78      0.78      0.78      1322
weighted avg       0.78      0.78      0.78      1322

Confusion Matrix:
[[529 132]
 [153 508]]


- Random Forests

In [78]:
from sklearn.ensemble import RandomForestClassifier

# Initialize Random Forest Classifier
random_forest = RandomForestClassifier(n_estimators=100, random_state=0)

# Fit the model on the training data
random_forest.fit(X_train, y_train)

# Predict on the test data
y_pred = random_forest.predict(X_test)

# Calculate and print performance metrics
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.80
Classification Report:
              precision    recall  f1-score   support

       False       0.79      0.81      0.80       661
        True       0.80      0.78      0.79       661

    accuracy                           0.80      1322
   macro avg       0.80      0.80      0.79      1322
weighted avg       0.80      0.80      0.79      1322

Confusion Matrix:
[[536 125]
 [146 515]]


- Gradient Boosting

In [80]:
from sklearn.ensemble import GradientBoostingClassifier

# Initialize Gradient Boosting Classifier
gradient_boosting = GradientBoostingClassifier(n_estimators=100, random_state=0)

# Fit the model on the training data
gradient_boosting.fit(X_train, y_train)

# Predict on the test data
y_pred = gradient_boosting.predict(X_test)

# Calculate and print performance metrics
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.79
Classification Report:
              precision    recall  f1-score   support

       False       0.82      0.74      0.78       661
        True       0.76      0.83      0.80       661

    accuracy                           0.79      1322
   macro avg       0.79      0.79      0.79      1322
weighted avg       0.79      0.79      0.79      1322

Confusion Matrix:
[[488 173]
 [110 551]]


- Adaptive Boosting

In [82]:
from sklearn.ensemble import AdaBoostClassifier

# Initialize AdaBoost Classifier with DecisionTreeClassifier as base estimator
adaboost_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1), n_estimators=50, random_state=0)

# Fit the model on the training data
adaboost_clf.fit(X_train, y_train)

# Predict on the test data
y_pred = adaboost_clf.predict(X_test)

# Calculate and print performance metrics
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

C:\Users\salto\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


Accuracy: 0.79
Classification Report:
              precision    recall  f1-score   support

       False       0.80      0.75      0.78       661
        True       0.77      0.82      0.79       661

    accuracy                           0.79      1322
   macro avg       0.79      0.79      0.78      1322
weighted avg       0.79      0.79      0.78      1322

Confusion Matrix:
[[498 163]
 [121 540]]


Which model is the best and why?

In [ ]:
#comment here