# LAB | Ensemble Methods

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In this Lab, you should try different ensemble methods in order to see if can obtain a better model than before. In order to do a fair comparison, you should perform the same feature scaling, engineering applied in previous Lab.

In [46]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [29]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

Now perform the same as before:
- Feature Scaling
- Feature Selection


In [30]:
#your code here
spaceship.dropna(inplace=True)
spaceship["Cabin"] = spaceship["Cabin"].astype(str).str[0]
spaceship.drop(columns=["PassengerId", "Name"], inplace=True)
spaceship = pd.get_dummies(spaceship)


**Perform Train Test Split**

In [31]:
#your code here
features = spaceship.drop(columns="Transported")
target = spaceship["Transported"]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(features, target)

In [33]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
normalizer = MinMaxScaler()

normalizer.fit(X_train)

MinMaxScaler()

In [34]:
X_train_norm = normalizer.transform(X_train)
X_test_norm = normalizer.transform(X_test)
X_train_norm = pd.DataFrame(X_train_norm, columns = X_train.columns)
X_train_norm.head()

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0  0.670886     0.000000   0.000000      0.068688  0.000000  0.000000   
1  0.481013     0.000000   0.025069      0.000000  0.002187  0.043076   
2  0.227848     0.000000   0.000000      0.001823  0.033515  0.000197   
3  0.253165     0.006872   0.000000      0.157905  0.073947  0.000000   
4  0.392405     0.238528   0.000000      0.099770  0.006069  0.000000   

   HomePlanet_Earth  HomePlanet_Europa  HomePlanet_Mars  CryoSleep_False  ...  \
0               1.0                0.0              0.0              1.0  ...   
1               1.0                0.0              0.0              1.0  ...   
2               1.0                0.0              0.0              1.0  ...   
3               0.0                0.0              1.0              1.0  ...   
4               0.0                0.0              1.0              1.0  ...   

   Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  Destination_55 Cancri e  \
0      0.0      0.0      1.0      0.0      0.0                      0.0   
1      0.0      1.0      0.0      0.0      0.0                      1.0   
2      0.0      0.0      0.0      1.0      0.0                      0.0   
3      1.0      0.0      0.0      0.0      0.0                      0.0   
4      1.0      0.0      0.0      0.0      0.0                      0.0   

   Destination_PSO J318.5-22  Destination_TRAPPIST-1e  VIP_False  VIP_True  
0                        0.0                      1.0        1.0       0.0  
1                        0.0                      0.0        1.0       0.0  
2                        1.0                      0.0        1.0       0.0  
3                        0.0                      1.0        1.0       0.0  
4                        0.0                      1.0        1.0       0.0  

[5 rows x 24 columns]

In [35]:
X_test_norm = pd.DataFrame(X_test_norm, columns = X_test.columns)
X_test_norm.head()

Age  RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
0  0.405063     0.000000   0.000000           0.0  0.010755  0.233920   
1  0.164557     0.000000   0.000000           0.0  0.000000  0.000000   
2  0.227848     0.000000   0.000361           0.0  0.000000  0.036290   
3  0.696203     0.000000   0.000000           0.0  0.000000  0.000000   
4  0.303797     0.004426   0.009270           0.0  0.002410  0.205744   

   HomePlanet_Earth  HomePlanet_Europa  HomePlanet_Mars  CryoSleep_False  ...  \
0               0.0                1.0              0.0              1.0  ...   
1               1.0                0.0              0.0              0.0  ...   
2               1.0                0.0              0.0              1.0  ...   
3               0.0                0.0              1.0              0.0  ...   
4               0.0                1.0              0.0              1.0  ...   

   Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  Destination_55 Cancri e  \
0      0.0      0.0      0.0      0.0      0.0                      0.0   
1      0.0      0.0      0.0      1.0      0.0                      0.0   
2      0.0      0.0      1.0      0.0      0.0                      0.0   
3      0.0      1.0      0.0      0.0      0.0                      0.0   
4      0.0      0.0      0.0      0.0      0.0                      1.0   

   Destination_PSO J318.5-22  Destination_TRAPPIST-1e  VIP_False  VIP_True  
0                        0.0                      1.0        1.0       0.0  
1                        0.0                      1.0        1.0       0.0  
2                        0.0                      1.0        1.0       0.0  
3                        0.0                      1.0        1.0       0.0  
4                        0.0                      0.0        1.0       0.0  

[5 rows x 24 columns]

In [41]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train_norm,y_train)
pred = log_reg.predict(X_test_norm)
pred

array([False,  True, False, ..., False,  True,  True])

In [47]:
accuracy_score(y_test,pred)

0.761501210653753

In [66]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=10)
tree.fit(X_train, y_train)
pred_dt = tree.predict(X_test)

pred_dt

array([False,  True, False, ...,  True,  True,  True])

In [67]:
target.unique()

array([False,  True])

In [68]:
accuracy_score(y_test, pred_dt)

0.7778450363196125

**Model Selection** - now you will try to apply different ensemble methods in order to get a better model

- Bagging and Pasting

In [11]:
#your code here

- Random Forests

In [ ]:
#your code here

- Gradient Boosting

In [ ]:
#your code here

- Adaptive Boosting

In [ ]:
#your code here

Which model is the best and why?

In [ ]:
#comment here